<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OpenGameAgent.Providers.MessageGateway.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenGameAgent\OpenGameAgent.csproj" />
    <ProjectReference Include="..\..\src\OpenGameAgent.Providers.MessageGateway\OpenGameAgent.Providers.MessageGateway.csproj" />
  </ItemGroup>
</Project>
