// Generated by tools/Generate-RuntimeProtocolSdks.ps1. Do not edit by hand.
// Runtime Protocol v1 schema SHA-256: c570963c38d9097521a47d3fb8b88297b68008411df97e88d7c2a98d3418fa90

export const PROTOCOL_VERSION = 1 as const;
export const MAXIMUM_JSON_CHARACTERS = 8_000_000;
export const MAXIMUM_PAGE_SIZE = 1_024;
export const MAXIMUM_SEQUENCE = 9_007_199_254_740_991;
export const SCHEMA_SHA256 = 'c570963c38d9097521a47d3fb8b88297b68008411df97e88d7c2a98d3418fa90';

export type RuntimeEventKind = 'run' | 'turn' | 'item' | 'result' | 'gap' | 'heartbeat';
export type RuntimeItemKind = 'message' | 'tool' | 'action' | 'approval' | 'interaction' | 'artifact' | 'delegation' | 'plan' | 'media' | 'status';
export type RuntimeLifecycle = 'started' | 'delta' | 'completed';
export type RuntimeControlStatus = 'accepted' | 'idle' | 'runNotStarted' | 'runMismatch' | 'turnMismatch' | 'controlClosed' | 'unauthorized';
export type RuntimeRunStatus = 'running' | 'completed' | 'stopped' | 'aborted' | 'failed' | 'unknown';

export interface RuntimeInitializeRequest {
  minimumVersion: number;
  maximumVersion: number;
  capabilities: string[];
}

export interface RuntimeInitializeResponse {
  version: 1;
  capabilities: string[];
  serverName: string;
  serverVersion: string;
}

export interface RuntimeStartRequest {
  requestId: string;
  inputJson: string;
}

export interface RuntimeControlRequest {
  sessionId: string;
  actorId: string;
  expectedRunId: string;
  expectedTurnId: string;
  expectedTurn: number;
  messageJson?: string | null;
}

export interface RuntimeControlResponse {
  status: RuntimeControlStatus;
  activeRunId: string | null;
  activeTurn: number | null;
  accepted: boolean;
}

export interface RuntimeReadEventsRequest {
  sessionId: string;
  actorId: string;
  afterSequence: number;
  maximum: number;
}

export interface RuntimeEventEnvelope {
  protocolVersion: 1;
  eventId: string;
  sequence: number;
  occurredAt: string;
  sessionId: string;
  actorId: string;
  inputId: string;
  runId: string | null;
  turn: number | null;
  turnId: string | null;
  itemId: string | null;
  eventKind: RuntimeEventKind;
  itemKind: RuntimeItemKind | null;
  lifecycle: RuntimeLifecycle;
  name: string;
  payloadJson: string;
  terminal: boolean;
}

export interface RuntimeEventPage {
  sessionId: string;
  actorId: string;
  requestedAfterSequence: number;
  firstRetainedSequence: number;
  lastSequence: number;
  nextAfterSequence: number;
  gap: boolean;
  events: RuntimeEventEnvelope[];
}

export interface RuntimeItemSnapshot {
  itemId: string;
  kind: RuntimeItemKind;
  lifecycle: RuntimeLifecycle;
  name: string;
  payloadJson: string;
  lastSequence: number;
}

export interface RuntimeRunSnapshot {
  sessionId: string;
  actorId: string;
  inputId: string;
  runId: string | null;
  turn: number | null;
  status: RuntimeRunStatus;
  lastSequence: number;
  items: RuntimeItemSnapshot[];
  resultJson: string | null;
  requiresTranscriptReconciliation: boolean;
}

const EVENT_KINDS = new Set<RuntimeEventKind>(['run', 'turn', 'item', 'result', 'gap', 'heartbeat']);
const ITEM_KINDS = new Set<RuntimeItemKind>(['message', 'tool', 'action', 'approval', 'interaction', 'artifact', 'delegation', 'plan', 'media', 'status']);
const LIFECYCLES = new Set<RuntimeLifecycle>(['started', 'delta', 'completed']);
const CONTROL_STATUSES = new Set<RuntimeControlStatus>(['accepted', 'idle', 'runNotStarted', 'runMismatch', 'turnMismatch', 'controlClosed', 'unauthorized']);
const EVENT_KEYS = new Set([
  'protocolVersion', 'eventId', 'sequence', 'occurredAt', 'sessionId', 'actorId', 'inputId',
  'runId', 'turn', 'turnId', 'itemId', 'eventKind', 'itemKind', 'lifecycle', 'name',
  'payloadJson', 'terminal',
]);
const INITIALIZE_RESPONSE_KEYS = new Set(['version', 'capabilities', 'serverName', 'serverVersion']);
const EVENT_PAGE_KEYS = new Set([
  'sessionId', 'actorId', 'requestedAfterSequence', 'firstRetainedSequence', 'lastSequence',
  'nextAfterSequence', 'gap', 'events',
]);
const CONTROL_RESPONSE_KEYS = new Set(['status', 'activeRunId', 'activeTurn', 'accepted']);

export class RuntimeProtocolError extends Error {
  readonly code: string;
  readonly status: number | null;

  constructor(code: string, message: string, status: number | null = null) {
    super(message);
    this.name = 'RuntimeProtocolError';
    this.code = code;
    this.status = status;
  }
}

function record(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new RuntimeProtocolError('invalid-shape', `${label} must be an object.`);
  }
  return value as Record<string, unknown>;
}

function exactKeys(value: Record<string, unknown>, expected: Set<string>, label: string): void {
  for (const key of Object.keys(value)) {
    if (!expected.has(key)) {
      throw new RuntimeProtocolError('unknown-field', `${label} contains an unknown field.`);
    }
  }
  for (const key of expected) {
    if (!(key in value)) {
      throw new RuntimeProtocolError('missing-field', `${label} is missing a required field.`);
    }
  }
}

function boundedId(value: unknown, label: string, maximum = 1_024): string {
  if (typeof value !== 'string' || value.length < 1 || value.length > maximum || /[\u0000-\u001f\u007f]/u.test(value)) {
    throw new RuntimeProtocolError('invalid-id', `${label} must be a bounded printable identifier.`);
  }
  return value;
}

function safeInteger(value: unknown, label: string, minimum = 0, maximum = MAXIMUM_SEQUENCE): number {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum || value > maximum) {
    throw new RuntimeProtocolError('invalid-integer', `${label} must be a bounded safe integer.`);
  }
  return value;
}

function boundedStrings(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || value.length > 256) {
    throw new RuntimeProtocolError('invalid-array', `${label} exceeds its boundary.`);
  }
  const result = value.map((item) => boundedId(item, label, 256));
  if (new Set(result).size !== result.length) {
    throw new RuntimeProtocolError('duplicate-value', `${label} must contain unique values.`);
  }
  return result;
}

export function parseJsonText(value: unknown, label = 'json'): unknown {
  if (typeof value !== 'string' || value.length > MAXIMUM_JSON_CHARACTERS) {
    throw new RuntimeProtocolError('invalid-json', `${label} exceeds the JSON boundary.`);
  }
  try {
    const parsed: unknown = JSON.parse(value);
    assertBoundedJsonSyntax(value, label);
    return parsed;
  } catch (error) {
    if (error instanceof RuntimeProtocolError) throw error;
    throw new RuntimeProtocolError('invalid-json', `${label} is not valid JSON.`);
  }
}

function assertBoundedJsonSyntax(value: string, label: string): void {
  let index = 0;

  const skipWhitespace = (): void => {
    while (index < value.length && /[\t\n\r ]/u.test(value[index])) index += 1;
  };

  const readString = (): string => {
    const start = index;
    index += 1;
    while (index < value.length) {
      const character = value[index++];
      if (character === '"') return JSON.parse(value.slice(start, index)) as string;
      if (character === '\\') {
        if (value[index] === 'u') index += 5;
        else index += 1;
      }
    }
    throw new RuntimeProtocolError('invalid-json', `${label} is not valid JSON.`);
  };

  const readValue = (depth: number): void => {
    skipWhitespace();
    if (value[index] === '{') {
      if (depth >= 128) throw new RuntimeProtocolError('json-too-deep', `${label} exceeds the JSON depth boundary.`);
      index += 1;
      skipWhitespace();
      const keys = new Set<string>();
      if (value[index] === '}') { index += 1; return; }
      while (index < value.length) {
        const key = readString();
        if (keys.has(key)) throw new RuntimeProtocolError('duplicate-field', `${label} contains a duplicate field.`);
        keys.add(key);
        skipWhitespace();
        index += 1; // JSON.parse already proved this byte is a colon.
        readValue(depth + 1);
        skipWhitespace();
        if (value[index++] === '}') return;
        skipWhitespace();
      }
    } else if (value[index] === '[') {
      if (depth >= 128) throw new RuntimeProtocolError('json-too-deep', `${label} exceeds the JSON depth boundary.`);
      index += 1;
      skipWhitespace();
      if (value[index] === ']') { index += 1; return; }
      while (index < value.length) {
        readValue(depth + 1);
        skipWhitespace();
        if (value[index++] === ']') return;
        skipWhitespace();
      }
    } else if (value[index] === '"') {
      readString();
    } else {
      while (index < value.length && !/[,\]}\t\n\r ]/u.test(value[index])) index += 1;
    }
  };

  readValue(0);
  skipWhitespace();
  if (index !== value.length) {
    throw new RuntimeProtocolError('invalid-json', `${label} is not valid JSON.`);
  }
}

export function parseRuntimeEvent(value: unknown): RuntimeEventEnvelope {
  const input = record(value, 'event');
  exactKeys(input, EVENT_KEYS, 'event');
  if (input.protocolVersion !== PROTOCOL_VERSION) {
    throw new RuntimeProtocolError('version-mismatch', 'The event protocol version is unsupported.');
  }
  const eventKind = input.eventKind;
  const lifecycle = input.lifecycle;
  if (typeof eventKind !== 'string' || !EVENT_KINDS.has(eventKind as RuntimeEventKind)
      || typeof lifecycle !== 'string' || !LIFECYCLES.has(lifecycle as RuntimeLifecycle)) {
    throw new RuntimeProtocolError('invalid-enum', 'The event kind or lifecycle is invalid.');
  }
  const itemKind = input.itemKind;
  if (itemKind !== null && (typeof itemKind !== 'string' || !ITEM_KINDS.has(itemKind as RuntimeItemKind))) {
    throw new RuntimeProtocolError('invalid-enum', 'The item kind is invalid.');
  }
  const runId = input.runId === null ? null : boundedId(input.runId, 'runId');
  const turn = input.turn === null ? null : safeInteger(input.turn, 'turn', 0, 1_000_000);
  const turnId = input.turnId === null ? null : boundedId(input.turnId, 'turnId');
  const itemId = input.itemId === null ? null : boundedId(input.itemId, 'itemId');
  if ((turn === null) !== (turnId === null) || (turnId !== null && runId === null)
      || (eventKind === 'item' && (itemId === null || itemKind === null))
      || (eventKind !== 'item' && (itemId !== null || itemKind !== null))
      || (input.terminal === true && lifecycle !== 'completed')) {
    throw new RuntimeProtocolError('invalid-coordinates', 'The event coordinates are inconsistent.');
  }
  if (typeof input.occurredAt !== 'string' || !Number.isFinite(Date.parse(input.occurredAt))) {
    throw new RuntimeProtocolError('invalid-date', 'occurredAt must be an RFC 3339 timestamp.');
  }
  if (typeof input.terminal !== 'boolean') {
    throw new RuntimeProtocolError('invalid-shape', 'terminal must be boolean.');
  }
  parseJsonText(input.payloadJson, 'payloadJson');
  boundedId(input.eventId, 'eventId');
  safeInteger(input.sequence, 'sequence');
  boundedId(input.sessionId, 'sessionId');
  boundedId(input.actorId, 'actorId');
  boundedId(input.inputId, 'inputId');
  boundedId(input.name, 'name', 256);
  return input as unknown as RuntimeEventEnvelope;
}

export function readEventSequence(eventId: string): number {
  boundedId(eventId, 'eventId');
  const prefix = 'oga-rp1-';
  if (!eventId.startsWith(prefix) || eventId.length < prefix.length + 17) {
    throw new RuntimeProtocolError('invalid-cursor', 'The Runtime event cursor is invalid.');
  }
  const digits = eventId.slice(prefix.length, prefix.length + 16);
  if (!/^[0-9a-fA-F]{16}$/u.test(digits)) {
    throw new RuntimeProtocolError('invalid-cursor', 'The Runtime event cursor is invalid.');
  }
  const value = Number.parseInt(digits, 16);
  if (!Number.isSafeInteger(value) || value < 1 || value > MAXIMUM_SEQUENCE) {
    throw new RuntimeProtocolError('invalid-cursor', 'The Runtime event cursor exceeds the safe range.');
  }
  return value;
}

interface MutableItem extends RuntimeItemSnapshot { firstSequence: number }

export class RuntimeReducer {
  private readonly items = new Map<string, MutableItem>();
  private sessionId: string | null = null;
  private actorId: string | null = null;
  private inputId: string | null = null;
  private runId: string | null = null;
  private turn: number | null = null;
  private status: RuntimeRunStatus = 'unknown';
  private lastSequence = 0;
  private resultJson: string | null = null;
  private reconcile = false;

  apply(raw: RuntimeEventEnvelope | unknown): void {
    const value = parseRuntimeEvent(raw);
    if (this.lastSequence > 0 && value.sequence !== this.lastSequence + 1) {
      throw new RuntimeProtocolError('sequence-gap', 'Runtime events must be contiguous.');
    }
    if (this.sessionId !== null && (this.sessionId !== value.sessionId || this.actorId !== value.actorId || this.inputId !== value.inputId)) {
      throw new RuntimeProtocolError('mixed-input', 'A reducer cannot combine different session actors or inputs.');
    }
    this.sessionId = value.sessionId;
    this.actorId = value.actorId;
    this.inputId = value.inputId;
    this.lastSequence = value.sequence;
    if (value.runId !== null) {
      if (this.runId !== null && this.runId !== value.runId) {
        throw new RuntimeProtocolError('mixed-run', 'A reducer cannot combine different runs.');
      }
      this.runId = value.runId;
    }
    if (value.turn !== null) this.turn = value.turn;
    if (value.eventKind === 'gap') this.reconcile = true;
    else if (value.eventKind === 'item') this.applyItem(value);
    else if (value.eventKind === 'run') this.applyRun(value);
    else if (value.eventKind === 'result') {
      this.resultJson = value.payloadJson;
      if (this.status === 'running' || this.status === 'unknown') this.status = 'completed';
    }
  }

  snapshot(): RuntimeRunSnapshot {
    if (this.sessionId === null || this.actorId === null || this.inputId === null) {
      throw new RuntimeProtocolError('empty-reducer', 'No Runtime event has been applied.');
    }
    return {
      sessionId: this.sessionId,
      actorId: this.actorId,
      inputId: this.inputId,
      runId: this.runId,
      turn: this.turn,
      status: this.status,
      lastSequence: this.lastSequence,
      items: [...this.items.values()].sort((a, b) => a.firstSequence - b.firstSequence).map(({ firstSequence: _, ...item }) => ({ ...item })),
      resultJson: this.resultJson,
      requiresTranscriptReconciliation: this.reconcile,
    };
  }

  private applyItem(value: RuntimeEventEnvelope): void {
    const id = value.itemId!;
    const existing = this.items.get(id);
    if (existing === undefined) {
      if (value.lifecycle !== 'started') throw new RuntimeProtocolError('item-lifecycle', 'An item must start first.');
      this.items.set(id, {
        itemId: id, kind: value.itemKind!, lifecycle: value.lifecycle, name: value.name,
        payloadJson: value.payloadJson, firstSequence: value.sequence, lastSequence: value.sequence,
      });
      return;
    }
    if (existing.lifecycle === 'completed' || value.lifecycle === 'started' || existing.kind !== value.itemKind) {
      throw new RuntimeProtocolError('item-lifecycle', 'The Runtime item lifecycle is invalid.');
    }
    existing.lifecycle = value.lifecycle;
    existing.name = value.name;
    existing.payloadJson = value.payloadJson;
    existing.lastSequence = value.sequence;
  }

  private applyRun(value: RuntimeEventEnvelope): void {
    if (value.lifecycle === 'started') {
      if (this.status !== 'unknown') throw new RuntimeProtocolError('run-lifecycle', 'A run can start only once.');
      this.status = 'running';
    } else if (value.lifecycle === 'completed') {
      this.status = value.name === 'run_completed' ? 'completed'
        : value.name === 'run_stopped' ? 'stopped'
          : value.name === 'run_aborted' ? 'aborted' : 'failed';
      if ([...this.items.values()].some((item) => item.lifecycle !== 'completed')) this.reconcile = true;
    }
  }
}

export interface RuntimeFetchResponse {
  ok: boolean;
  status: number;
  text(): Promise<string>;
  body: { getReader(): { read(): Promise<{ done: boolean; value?: Uint8Array }>; cancel(): Promise<void>; releaseLock(): void } } | null;
}

export interface RuntimeFetchInit {
  method: 'POST';
  headers: Record<string, string>;
  body: string;
  signal?: unknown;
}

export type RuntimeFetch = (url: string, init: RuntimeFetchInit) => Promise<RuntimeFetchResponse>;

export interface RuntimeClientOptions {
  baseUrl: string;
  fetch?: RuntimeFetch;
  headers?: Record<string, string>;
  presentedCredential?: string;
  allowInsecureHttp?: boolean;
  maximumResponseCharacters?: number;
  maximumEventCharacters?: number;
}

export interface RuntimeStreamResult {
  lastEventId: string | null;
  lastSequence: number;
  terminal: boolean;
  requiresTranscriptReconciliation: boolean;
}

export class RuntimeClient {
  private readonly baseUrl: URL;
  private readonly fetcher: RuntimeFetch;
  private readonly headers: Record<string, string>;
  private readonly credential: string | null;
  private readonly maxResponse: number;
  private readonly maxEvent: number;

  constructor(options: RuntimeClientOptions) {
    this.baseUrl = new URL(options.baseUrl);
    if (!['http:', 'https:'].includes(this.baseUrl.protocol) || this.baseUrl.username || this.baseUrl.password || this.baseUrl.search || this.baseUrl.hash) {
      throw new RuntimeProtocolError('invalid-origin', 'The Runtime base URL is invalid.');
    }
    const local = ['localhost', '127.0.0.1', '::1', '[::1]'].includes(this.baseUrl.hostname);
    if (this.baseUrl.protocol === 'http:' && !local && options.allowInsecureHttp !== true) {
      throw new RuntimeProtocolError('insecure-origin', 'Remote Runtime servers must use HTTPS.');
    }
    const globalFetch = (globalThis as unknown as { fetch?: RuntimeFetch }).fetch;
    this.fetcher = options.fetch ?? globalFetch ?? (() => Promise.reject(new RuntimeProtocolError('missing-fetch', 'No fetch implementation is available.')));
    this.headers = { ...(options.headers ?? {}) };
    this.credential = options.presentedCredential ?? null;
    if (this.credential !== null && (this.credential.length > 4_096 || /[\r\n\0]/u.test(this.credential))) {
      throw new RuntimeProtocolError('invalid-credential', 'The presented credential is invalid.');
    }
    this.maxResponse = options.maximumResponseCharacters ?? MAXIMUM_JSON_CHARACTERS;
    this.maxEvent = options.maximumEventCharacters ?? MAXIMUM_JSON_CHARACTERS;
    if (this.maxResponse < 2 || this.maxResponse > MAXIMUM_JSON_CHARACTERS || this.maxEvent < 2 || this.maxEvent > MAXIMUM_JSON_CHARACTERS) {
      throw new RuntimeProtocolError('invalid-boundary', 'The configured response boundary is invalid.');
    }
  }

  async initialize(request: RuntimeInitializeRequest = { minimumVersion: 1, maximumVersion: 1, capabilities: [] }, signal?: unknown): Promise<RuntimeInitializeResponse> {
    safeInteger(request.minimumVersion, 'minimumVersion', 1);
    safeInteger(request.maximumVersion, 'maximumVersion', request.minimumVersion);
    boundedStrings(request.capabilities, 'capabilities');
    const value = await this.post('runtime/v1/initialize', request, signal);
    const result = record(value, 'initialize response');
    exactKeys(result, INITIALIZE_RESPONSE_KEYS, 'initialize response');
    if (result.version !== 1) throw new RuntimeProtocolError('invalid-response', 'The initialize response is invalid.');
    boundedStrings(result.capabilities, 'capabilities');
    boundedId(result.serverName, 'serverName', 256);
    boundedId(result.serverVersion, 'serverVersion', 256);
    return result as unknown as RuntimeInitializeResponse;
  }

  async readEvents(request: RuntimeReadEventsRequest, signal?: unknown): Promise<RuntimeEventPage> {
    boundedId(request.sessionId, 'sessionId'); boundedId(request.actorId, 'actorId');
    safeInteger(request.afterSequence, 'afterSequence'); safeInteger(request.maximum, 'maximum', 1, MAXIMUM_PAGE_SIZE);
    const value = record(await this.post('runtime/v1/events', { ...request, credential: this.credential }, signal), 'event page');
    exactKeys(value, EVENT_PAGE_KEYS, 'event page');
    if (value.sessionId !== request.sessionId || value.actorId !== request.actorId || !Array.isArray(value.events)) {
      throw new RuntimeProtocolError('invalid-response', 'The event page belongs to a different session actor.');
    }
    const requested = safeInteger(value.requestedAfterSequence, 'requestedAfterSequence');
    const first = safeInteger(value.firstRetainedSequence, 'firstRetainedSequence');
    const last = safeInteger(value.lastSequence, 'lastSequence');
    const next = safeInteger(value.nextAfterSequence, 'nextAfterSequence');
    if (requested !== request.afterSequence || typeof value.gap !== 'boolean' || value.events.length > MAXIMUM_PAGE_SIZE
        || next < requested || next > Math.max(last, requested) || first > last + 1) {
      throw new RuntimeProtocolError('invalid-response', 'The event page cursor fields are invalid.');
    }
    const events = value.events.map(parseRuntimeEvent);
    let previousSequence = value.gap ? first - 1 : requested;
    for (const event of events) {
      if (event.sessionId !== request.sessionId || event.actorId !== request.actorId
          || event.sequence <= previousSequence || event.sequence > next) {
        throw new RuntimeProtocolError('invalid-response', 'The event page contains an invalid event sequence or owner.');
      }
      previousSequence = event.sequence;
    }
    return { ...value, events } as unknown as RuntimeEventPage;
  }

  steer(request: RuntimeControlRequest, signal?: unknown): Promise<RuntimeControlResponse> {
    if (request.messageJson == null) throw new RuntimeProtocolError('invalid-control', 'Steer requires messageJson.');
    return this.control('runtime/v1/control/steer', request, signal);
  }

  interrupt(request: RuntimeControlRequest, signal?: unknown): Promise<RuntimeControlResponse> {
    return this.control('runtime/v1/control/interrupt', request, signal);
  }

  async stream(start: RuntimeStartRequest, onEvent: (event: RuntimeEventEnvelope) => void | Promise<void>, lastEventId: string | null = null, signal?: unknown): Promise<RuntimeStreamResult> {
    boundedId(start.requestId, 'requestId'); parseJsonText(start.inputJson, 'inputJson');
    let lastSequence = lastEventId === null ? 0 : readEventSequence(lastEventId);
    const headers = this.requestHeaders();
    headers.Accept = 'text/event-stream';
    if (lastEventId !== null) headers['Last-Event-ID'] = lastEventId;
    const response = await this.fetcher(this.endpoint('runtime/v1/run/stream'), {
      method: 'POST', headers, body: JSON.stringify({ ...start, credential: this.credential }), signal,
    });
    if (!response.ok) throw new RuntimeProtocolError('http-error', `Runtime request failed with HTTP ${response.status}.`, response.status);
    if (response.body === null) throw new RuntimeProtocolError('missing-body', 'The Runtime stream body is missing.');
    let eventName = 'message'; let id: string | null = null; let data: string[] = [];
    let terminal = false; let gap = false; let currentLastId = lastEventId;
    for await (const line of readLines(response.body.getReader(), this.maxEvent)) {
      if (line.startsWith('event:')) eventName = line.slice(6).trim();
      else if (line.startsWith('id:')) { id = line.slice(3).trim(); readEventSequence(id); }
      else if (line.startsWith('data:')) {
        data.push(line.slice(5).trimStart());
        if (data.join('\n').length > this.maxEvent) throw new RuntimeProtocolError('event-too-large', 'A Runtime event exceeded its boundary.');
      } else if (line.length === 0 && data.length > 0) {
        const payload = data.join('\n');
        if (eventName === 'gap') {
          const gapValue = record(parseJsonText(payload, 'gap'), 'gap');
          if (gapValue.requiresTranscriptReconciliation !== true) throw new RuntimeProtocolError('invalid-gap', 'The Runtime gap event is invalid.');
          gap = true; currentLastId = null; lastSequence = 0;
        } else if (eventName === 'runtime') {
          const value = parseRuntimeEvent(parseJsonText(payload, 'event'));
          if (id === null || id !== value.eventId || value.sequence <= lastSequence) throw new RuntimeProtocolError('invalid-stream-order', 'Runtime SSE IDs must match and advance.');
          currentLastId = id; lastSequence = value.sequence; terminal = value.terminal;
          await onEvent(value);
        } else throw new RuntimeProtocolError('unsupported-sse-event', 'The server emitted an unsupported Runtime SSE event.');
        eventName = 'message'; id = null; data = [];
        if (terminal) break;
      }
    }
    return { lastEventId: currentLastId, lastSequence, terminal, requiresTranscriptReconciliation: gap };
  }

  private async control(path: string, request: RuntimeControlRequest, signal?: unknown): Promise<RuntimeControlResponse> {
    boundedId(request.sessionId, 'sessionId'); boundedId(request.actorId, 'actorId'); boundedId(request.expectedRunId, 'expectedRunId'); boundedId(request.expectedTurnId, 'expectedTurnId');
    safeInteger(request.expectedTurn, 'expectedTurn', 1, 1_000_000);
    if (request.messageJson != null) parseJsonText(request.messageJson, 'messageJson');
    const value = record(await this.post(path, { ...request, credential: this.credential }, signal), 'control response');
    exactKeys(value, CONTROL_RESPONSE_KEYS, 'control response');
    if (typeof value.status !== 'string' || !CONTROL_STATUSES.has(value.status as RuntimeControlStatus) || typeof value.accepted !== 'boolean') {
      throw new RuntimeProtocolError('invalid-response', 'The control response is invalid.');
    }
    if (value.activeRunId !== null) boundedId(value.activeRunId, 'activeRunId');
    if (value.activeTurn !== null) safeInteger(value.activeTurn, 'activeTurn', 0, 1_000_000);
    return value as unknown as RuntimeControlResponse;
  }

  private async post(path: string, value: unknown, signal?: unknown): Promise<unknown> {
    const body = JSON.stringify(value);
    if (body.length > MAXIMUM_JSON_CHARACTERS) throw new RuntimeProtocolError('request-too-large', 'The Runtime request exceeds its boundary.');
    const response = await this.fetcher(this.endpoint(path), { method: 'POST', headers: this.requestHeaders(), body, signal });
    if (!response.ok) throw new RuntimeProtocolError('http-error', `Runtime request failed with HTTP ${response.status}.`, response.status);
    const text = await response.text();
    if (text.length > this.maxResponse) throw new RuntimeProtocolError('response-too-large', 'The Runtime response exceeds its boundary.');
    return parseJsonText(text, 'response');
  }

  private endpoint(path: string): string {
    const value = new URL(path, this.baseUrl);
    if (value.origin !== this.baseUrl.origin) throw new RuntimeProtocolError('cross-origin-path', 'A Runtime endpoint changed origin.');
    return value.toString();
  }

  private requestHeaders(): Record<string, string> { return { 'Content-Type': 'application/json', ...this.headers }; }
}

async function* readLines(reader: { read(): Promise<{ done: boolean; value?: Uint8Array }>; cancel(): Promise<void>; releaseLock(): void }, maximum: number): AsyncGenerator<string> {
  const decoder = new TextDecoder(); let pending = '';
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      pending += decoder.decode(value, { stream: true });
      if (pending.length > maximum) throw new RuntimeProtocolError('line-too-large', 'A Runtime SSE line exceeds its boundary.');
      let index: number;
      while ((index = pending.indexOf('\n')) >= 0) {
        let line = pending.slice(0, index); pending = pending.slice(index + 1);
        if (line.endsWith('\r')) line = line.slice(0, -1);
        yield line;
      }
    }
    pending += decoder.decode();
    if (pending.length > 0) yield pending.endsWith('\r') ? pending.slice(0, -1) : pending;
  } finally {
    reader.releaseLock();
  }
}
